#name: Deploy to NPM
#
#on:
#  # nightly job
#  schedule:
#    - cron: '0 12 * * *'
#  # triggered by repo
#  repository_dispatch:
#
#jobs:
#
#  build:
#    name: Check out framework and compiler, create unified codebase, and compile
#    run: #
#
#  semantic_release:
#    name: Release to NPM using semantic release
#    run: #
